### ISSUE TITLE
Please, add a mouseviz option.

### ISSUE THREAD

**Issue by krasnovpro** [mulaRahul/keyviz#112] opened 2023-03-14 11:32 UTC
Left/middle/right mouse buttons and wheelup/wheeldown.

**Comment by mulaRahul** [comment] 2023-03-15 06:49
[Future Plans](https://github.com/mulaRahul/keyviz/discussions/36#discussioncomment-4352731)

**Comment by mulaRahul** [comment] 2023-06-18 04:53
duplicate of #101

**Closed by mulaRahul** 2023-06-18 04:53 UTC
