### ISSUE TITLE
The content displayed by pressing the space is empty.

### ISSUE THREAD

**Issue by xing403** [mulaRahul/keyviz#182] opened 2023-09-02 12:33 UTC
**Describe the bug**
For example, when I press `LeftArrow`, `Left` is displayed. 
But when I press `Space`, it shows an empty space instead of `space`
![1693657889864](https://github.com/mulaRahul/keyviz/assets/74746021/b1408df2-15d7-4437-8d8b-413577e85415)

**Version**: v2.0.0-alpha

**Comment by mulaRahul** [comment] 2024-04-21 15:17
Duplicate of #158

**Closed by mulaRahul** 2024-04-21 15:17 UTC
