### ISSUE TITLE
The key cannot disappear automatically when the headset switches to the previous song or the next song.

### ISSUE THREAD

**Issue by Web0706** [mulaRahul/keyviz#189] opened 2023-09-19 02:30 UTC
![image](https://github.com/mulaRahul/keyviz/assets/103833016/0fcf0cb0-7a4e-460f-9e30-05811ece38fd)

**Comment by mulaRahul** [comment] 2024-01-11 11:02
Can you reproduce the same in [v2.0.0a](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a)?

**Comment by mulaRahul** [comment] 2024-09-19 11:09
Closing due to lack of further context.

**Closed by mulaRahul** 2024-09-19 11:09 UTC
